version: "3"

services:
  app:
    build:
      context: docker
      dockerfile: development/app/Dockerfile
    volumes:
      - .:/var/www/html/

  phpstan:
    image: ghcr.io/phpstan/phpstan
    volumes:
      - .:/app/
